# Generated by Django 4.2.7 on 2023-11-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='gd_maximo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='gd_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
