# Generated by Django 4.2.7 on 2023-11-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produto_gd_maximo_produto_gd_minimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='gd_maximo',
            new_name='gd_maximo_acum',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='gd_minimo',
            new_name='gd_minimo_acum',
        ),
        migrations.AddField(
            model_name='produto',
            name='temp_basal',
            field=models.IntegerField(default=0),
        ),
    ]
