# Generated by Django 4.2.7 on 2023-11-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_testestestesteste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CulturaPlantacao',
            new_name='CulturaPlantacaoCadastro',
        ),
        migrations.RenameModel(
            old_name='GD',
            new_name='GrauDia',
        ),
        migrations.RenameModel(
            old_name='Previsao',
            new_name='MediaGrauDia',
        ),
        migrations.RenameModel(
            old_name='MediaGD',
            new_name='PrevisaoEstimada',
        ),
        migrations.RenameModel(
            old_name='Sensor',
            new_name='SensorDeteccao',
        ),
        migrations.RenameModel(
            old_name='SomaTermica',
            new_name='SomaTermicaCalculada',
        ),
        migrations.RenameModel(
            old_name='Temperatura',
            new_name='TemperaturaDetectada',
        ),
        migrations.RenameField(
            model_name='mediagraudia',
            old_name='data_previsao',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='mediagraudia',
            old_name='valor_previsao',
            new_name='valor_media',
        ),
        migrations.RenameField(
            model_name='previsaoestimada',
            old_name='data',
            new_name='data_previsao',
        ),
        migrations.RenameField(
            model_name='previsaoestimada',
            old_name='valor_media',
            new_name='valor_previsao',
        ),
    ]
