# Generated by Django 4.2.7 on 2023-11-18 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_gd_maximo_produto_gd_maximo_acum_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='CulturaPlantacao',
        ),
    ]
