# Generated by Django 4.2.7 on 2023-11-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_culturaplantacao_culturaplantacaocadastro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CulturaPlantacaoCadastro',
            new_name='CulturaPlantacao',
        ),
        migrations.RenameModel(
            old_name='GrauDia',
            new_name='GD',
        ),
        migrations.RenameModel(
            old_name='PrevisaoEstimada',
            new_name='MediaGD',
        ),
        migrations.RenameModel(
            old_name='MediaGrauDia',
            new_name='Previsao',
        ),
        migrations.RenameModel(
            old_name='SensorDeteccao',
            new_name='Sensor',
        ),
        migrations.RenameModel(
            old_name='SomaTermicaCalculada',
            new_name='SomaTermica',
        ),
        migrations.RenameModel(
            old_name='TemperaturaDetectada',
            new_name='Temperatura',
        ),
        migrations.DeleteModel(
            name='TESTESTESTESTESTE',
        ),
        migrations.RenameField(
            model_name='mediagd',
            old_name='data_previsao',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='mediagd',
            old_name='valor_previsao',
            new_name='valor_media',
        ),
        migrations.RenameField(
            model_name='previsao',
            old_name='data',
            new_name='data_previsao',
        ),
        migrations.RenameField(
            model_name='previsao',
            old_name='valor_media',
            new_name='valor_previsao',
        ),
    ]
