# Generated by Django 4.2.7 on 2023-11-29 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_culturaplantacaocadastro_culturaplantacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESTECulturaPlantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('gd_maximo_acum', models.IntegerField(default=0)),
                ('gd_minimo_acum', models.IntegerField(default=0)),
                ('temp_basal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TESTESensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sensor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TESTETemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(default=0.0)),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.testesensor')),
            ],
        ),
        migrations.CreateModel(
            name='TESTESomaTermica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soma_atual', models.FloatField()),
                ('data_insercao', models.DateTimeField(default=datetime.datetime.now)),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.testeculturaplantacao')),
            ],
        ),
        migrations.CreateModel(
            name='TESTEPrevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_previsao', models.FloatField()),
                ('data_previsao', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('data_insercao', models.DateTimeField(default=datetime.datetime.now)),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.testeculturaplantacao')),
            ],
        ),
        migrations.CreateModel(
            name='TESTEMediaGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_media', models.FloatField()),
                ('data_insercao', models.DateTimeField(default=datetime.datetime.now)),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.testeculturaplantacao')),
            ],
        ),
        migrations.CreateModel(
            name='TESTEGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_gd', models.FloatField()),
                ('data_gd', models.DateField(auto_now_add=True)),
                ('temperatura_max', models.FloatField(default=0.0)),
                ('temperatura_min', models.FloatField(default=0.0)),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.testeculturaplantacao')),
            ],
        ),
        migrations.AddField(
            model_name='testeculturaplantacao',
            name='fk_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.testesensor'),
        ),
    ]
