# Generated by Django 4.2.7 on 2023-11-22 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_produto_culturaplantacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sensor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(default=0.0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='culturaplantacao',
            name='fk_sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.sensor'),
            preserve_default=False,
        ),
    ]
