# Generated by Django 4.2.7 on 2023-11-29 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_testeculturaplantacao_testesensor_testetemperatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemediagd',
            name='data_insercao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testeprevisao',
            name='data_insercao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testesomatermica',
            name='data_insercao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
