# Generated by Django 4.2.7 on 2023-11-24 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sensor_temperatura_culturaplantacao_fk_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='GD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_gd', models.FloatField()),
                ('data_gd', models.DateField(auto_now_add=True)),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.culturaplantacao')),
            ],
        ),
    ]
