# Generated by Django 4.2.7 on 2023-12-01 23:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_testemediagd_data_insercao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagd',
            name='data_insercao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='previsao',
            name='data_insercao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='previsao',
            name='data_previsao',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='somatermica',
            name='data_insercao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
    ]
