# Generated by Django 4.2.7 on 2023-11-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_temperatura_data_gd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomaTermica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soma_atual', models.FloatField()),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.culturaplantacao')),
            ],
        ),
    ]
