# Generated by Django 4.2.7 on 2023-11-24 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_somatermica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_previsao', models.FloatField()),
                ('data_previsao', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.culturaplantacao')),
            ],
        ),
        migrations.CreateModel(
            name='MediaGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_media', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('fk_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.culturaplantacao')),
            ],
        ),
    ]
